spring.application.name=academic-management-api
spring.main.banner-mode=console
spring.output.ansi.enabled=ALWAYS
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.config.import=optional:file:.env[.properties]
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.javax.persistence.validation.mode=none
spring.test.database.replace=NONE
security.jwt.secret=${JWT_SECRET:troque-esta-chave-por-uma-chave-segura}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}