name: CI/CD com Reviewdog
on: [push, pull_request]

permissions:
  pull-requests: write
  checks: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.5.0
        with:
          reviewdog_version: latest

      - name: Test
        run: ./gradlew test

      - name: Checkstyle Main
        run: ./gradlew checkstyleMain

      - name: Reviewdog Main
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: reviewdog -f=checkstyle -reporter=github-pr-review -filter-mode=added -level=warning < build/reports/checkstyle/main.xml
